#!/usr/bin/env python3
"""Build the SLOOP 2.4 Japanese UI PDF from current host/browser evidence.

SLOOP_PDF_FONT selects a static Noto Sans JP TTF. Native 240x240 captures
are generated by the firmware's drawing code in the host test, not a camera.
"""
import io
import json
import os
from pathlib import Path

from PIL import Image
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

ROOT = Path(__file__).resolve().parents[1]
E = ROOT / "docs/ja-ui-evidence"
OUT = ROOT / "docs/ja-ui-report.pdf"
FONT = Path(os.environ.get("SLOOP_PDF_FONT", ROOT / "build/deps/NotoSansJP-500.ttf"))
if not FONT.is_file():
    raise SystemExit(f"static Noto Sans JP font missing: {FONT}")
pdfmetrics.registerFont(TTFont("NotoJP", str(FONT)))
manifest = json.loads((E / "lcd-manifest.json").read_text())
layout = json.loads((E / "browser-layout.json").read_text())
scroll = json.loads((E / "scroll-capture.json").read_text())["results"]
metrics_file = E / "metrics.json"
metrics = json.loads(metrics_file.read_text()) if metrics_file.exists() else {}
fw = metrics.get("firmware", {})
W, H = A4
M = 38
INK = colors.HexColor("#182536")
MUTED = colors.HexColor("#53657a")
BLUE = colors.HexColor("#1268a4")
PALE = colors.HexColor("#eef4f9")
WHITE = colors.white
pdf = canvas.Canvas(str(OUT), pagesize=A4, pageCompression=1)
pdf.setTitle("SLOOP 2.4 日本語UI 画面・検証レポート")
pdf.setAuthor("Azsoft-jp SLOOP localization review")
page_no = 0


def text(x, y, value, size=9, color=INK):
    pdf.setFont("NotoJP", size)
    pdf.setFillColor(color)
    pdf.drawString(x, y, str(value))


def paragraph(x, y, value, width, size=9, leading=14):
    line = ""
    for ch in value:
        if ch == "\n" or (line and pdfmetrics.stringWidth(line + ch, "NotoJP", size) > width):
            text(x, y, line, size)
            y -= leading
            line = "" if ch == "\n" else ch
        else:
            line += ch
    if line:
        text(x, y, line, size)
        y -= leading
    return y


def start(section, title, subtitle=""):
    global page_no
    page_no += 1
    pdf.setFillColor(WHITE)
    pdf.rect(0, 0, W, H, fill=1, stroke=0)
    pdf.setFillColor(INK)
    pdf.rect(0, H - 58, W, 58, fill=1, stroke=0)
    text(M, H - 25, "SLOOP 2.4 / FM-1 / 日本語UI", 11, WHITE)
    text(M, H - 44, section, 8, colors.HexColor("#c4deee"))
    text(M, H - 91, title, 18)
    if subtitle:
        paragraph(M, H - 110, subtitle, W - 2 * M, 8, 11)


def finish():
    pdf.setStrokeColor(colors.HexColor("#d9e1ea"))
    pdf.line(M, 35, W - M, 35)
    text(M, 22, "ホスト描画・ブラウザーモックの証跡 / 実機表示と音声遅延は未確認", 7, MUTED)
    text(W - M - 18, 22, page_no, 8, MUTED)
    pdf.showPage()


def draw_image(path, x, y, width, crop=None):
    with Image.open(path) as original:
        image = original.convert("RGB")
        if crop:
            image = image.crop(crop)
        stream = io.BytesIO()
        image.save(stream, format="PNG")
    stream.seek(0)
    pdf.drawImage(ImageReader(stream), x, y, width, width * image.height / image.width)


def size(key):
    value = fw.get(key)
    return f"{value:,} B" if isinstance(value, int) else "未測定"


start("概要", "画面・検証レポート", "Phase 1 Web Editor / Phase 2 FM-1本体 - フォーク内レビュー")
text(M, 690, "240×240pxの本体描画を元画像のまま収録", 10)
paragraph(M, 670, "本体画像は実ファームウェアの描画関数をホスト上で動かした画面です。実機LCDの写真ではありません。Web画面はChromeのモック接続で撮影しました。", W - 2 * M, 8.4)
for i, name in enumerate(("menu-screen", "page-step")):
    x = M + i * 256
    draw_image(E / "lcd" / f"{name}.png", x, 376, 240)
    text(x, 363, name, 8, MUTED)
pdf.setFillColor(PALE)
pdf.roundRect(M, 258, W - 2 * M, 88, 8, fill=1, stroke=0)
text(M + 14, 325, f"{len(manifest)}画面 / {metrics.get('glyphs', '75')} glyph / {metrics.get('string_ids', '222')}文字列ID", 12, BLUE)
text(M + 14, 304, f"上流2.4 FW: {size('baseline_bytes')} → 日本語版: {size('localized_bytes')}", 9)
text(M + 14, 286, f"RAM (.data+.bss): {size('baseline_ram')} → {size('localized_ram')}", 9)
text(M + 14, 270, f"アプリ領域の残り: {size('localized_slot_free_bytes')}", 8)
text(M, 236, "確認したこと", 10)
paragraph(M, 218, f"本体描画・UTF-8・メニュー・保存読み込みのホストテスト、2.4操作ストレス、Webプロトコル試験。Webは375pxと1280pxで{len(layout)}画面を計測し、横はみ出しとパラメーター名の切れを検査しました。", W - 2 * M, 8.5)
text(M, 141, "制限", 10)
paragraph(M, 123, "実機LCDの色・視認性、音声割り込みの最大時間、実機からの保存・読み込みは未確認です。文字スクロールは追加していません。画面内に収まる短い語と小さい英字ラベルを使います。", W - 2 * M, 8.5)
finish()

for sheet in range((len(manifest) + 8) // 9):
    items = manifest[sheet * 9:(sheet + 1) * 9]
    start("FM-1 本体 / 実ピクセル", f"LCD画面 {sheet + 1} / {(len(manifest) + 8) // 9}",
          "元の240×240 PNGはdocs/ja-ui-evidence/lcd/にあります。")
    for j, entry in enumerate(items):
        col, row = j % 3, j // 3
        x, y = M + col * 175, 520 - row * 207
        pdf.setFillColor(PALE)
        pdf.roundRect(x, y, 166, 190, 6, fill=1, stroke=0)
        draw_image(E / "lcd" / f"{entry['screen']}.png", x + 11, y + 26, 145)
        text(x + 9, y + 10, entry["screen"], 7.5, MUTED)
    finish()

web = list(zip(("sound", "sequencer", "tracks", "library", "samples", "kits", "projects", "settings"),
               ("音色", "シーケンサー", "トラック", "ライブラリ", "サンプル", "ドラムキット", "プロジェクト", "設定")))
web.append(("installer", "インストーラー"))
for sheet in range((len(web) + 5) // 6):
    start("Web Editor / 375px Chrome", f"Web画面 {sheet + 1} / {(len(web) + 5) // 6}",
          "全長PNGはdocs/ja-ui-evidence/に収録。ここでは上部を切り出しています。")
    for j, (name, label) in enumerate(web[sheet * 6:(sheet + 1) * 6]):
        col, row = j % 3, j // 3
        x, y = M + col * 175, 390 - row * 310
        pdf.setFillColor(PALE)
        pdf.roundRect(x, y, 166, 296, 6, fill=1, stroke=0)
        path = E / ("installer-375.png" if name == "installer" else f"editor-375-{name}.png")
        draw_image(path, x + 6, y + 21, 154, (0, 0, 375, 630))
        text(x + 8, y + 8, label, 8, MUTED)
    finish()

for sheet in range((len(scroll) + 4) // 5):
    start("モバイル縦スクロール", f"GIFの開始・終了フレーム {sheet + 1} / {(len(scroll) + 4) // 5}",
          "動くGIF本体はHTMLレポートで再生できます。")
    for j, entry in enumerate(scroll[sheet * 5:(sheet + 1) * 5]):
        y = 587 - j * 128
        with Image.open(E / entry["gif"]) as gif:
            first = gif.convert("RGB")
            gif.seek(gif.n_frames - 1)
            last = gif.convert("RGB")
        for frame, x in ((first, M), (last, M + 64)):
            stream = io.BytesIO()
            frame.save(stream, format="PNG")
            stream.seek(0)
            pdf.drawImage(ImageReader(stream), x, y, 56, 122)
        text(M + 138, y + 84, entry["label"], 10)
        text(M + 138, y + 62, f"{entry['frames']} frames / {entry['height']}px", 8, MUTED)
    finish()

pdf.save()
print(f"{OUT}: {page_no} pages, {len(manifest)} LCD screens, {len(web)} web views, {len(scroll)} GIFs")
