#!/usr/bin/env python3
"""Convert host LCD test PPMs to native 240x240 PNG review evidence.

Run after tests/ui_pages_test and tests/song_ui_test have written build/host.
The PPMs are emitted by the firmware's own drawing code on a host framebuffer.
"""
from pathlib import Path
import json
import os
import sys

from PIL import Image, ImageDraw, ImageFont

src = Path(sys.argv[1] if len(sys.argv) > 1 else "build/host")
out = Path(sys.argv[2] if len(sys.argv) > 2 else "docs/ja-ui-evidence")
screens = out / "lcd"
screens.mkdir(parents=True, exist_ok=True)

# An old comparison file from the first localization pass is not a current
# screen; song-screen.ppm is regenerated by tests/song_ui_test.c.
sources = sorted(p for p in src.glob("*.ppm") if p.stem != "song-screen-ja")
if len(sources) < 35:
    raise SystemExit(f"expected at least 35 current LCD screens, found {len(sources)}")

selected = {"page-step", "page-song", "menu-audio", "menu-screen", "live-rec-free", "layer-song-chain", "layer-mix-fill"}
contact = Image.new("RGB", (6 * 240, ((len(sources) + 5) // 6) * 265), (0, 0, 0))
draw = ImageDraw.Draw(contact)
font = ImageFont.load_default()
manifest = []
for index, ppm in enumerate(sources):
    with Image.open(ppm) as source:
        if source.size != (240, 240):
            raise SystemExit(f"{ppm}: expected 240x240, got {source.size}")
        im = source.convert("RGB")
    target = screens / f"{ppm.stem}.png"
    im.save(target, optimize=True)
    if ppm.stem in selected:
        im.save(out / f"{ppm.stem}.png", optimize=True)
    x, y = (index % 6) * 240, (index // 6) * 265
    contact.paste(im, (x, y))
    draw.text((x + 3, y + 242), ppm.stem, font=font, fill=(220, 225, 235))
    manifest.append({"screen": ppm.stem, "source": os.path.relpath(ppm),
                     "image": os.path.relpath(target), "width": 240, "height": 240})

contact.save(out / "firmware-contact.png", optimize=True)
(out / "lcd-manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
if len(sys.argv) > 3:
    with Image.open(sys.argv[3]) as baseline:
        old = baseline.convert("RGB").resize((240, 240), Image.Resampling.NEAREST)
    with Image.open(screens / "page-step.png") as rendered:
        current = rendered.convert("RGB")
    comparison = Image.new("RGB", (480, 265), (24, 28, 35))
    comparison.paste(old, (0, 25))
    comparison.paste(current, (240, 25))
    labels = ImageDraw.Draw(comparison)
    labels.text((8, 7), "BEFORE 1bpp", font=font, fill="white")
    labels.text((248, 7), "AFTER 2bpp + crop fix", font=font, fill="white")
    comparison.save(out / "font-before-after.png", optimize=True)
print(f"{len(manifest)} native 240x240 LCD screens, {len(selected)} featured images, one contact sheet")
